import type { Metadata } from "next";
import "./globals.css";
import "../styles/magnific-popup.css";
import "../styles/tooplate-clean-work.css";
import "../styles/custom-bootstrap-icons.css";
import "bootstrap/dist/css/bootstrap.min.css";

import Header from "../components/header";

export const metadata: Metadata = {
  title: "Namba",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
